{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quickwit.fullname" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- if .Values.config.postgres }}
  postgres.password: {{ required "A valid config.postgres.password is required!" .Values.config.postgres.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.s3 }}
  s3.secret_key: {{ required "A valid config.s3.secret_key is required!" .Values.config.s3.secret_key | b64enc | quote }}
  {{- end }}
{{- end -}}